name: Zbuduj StatusLyrics APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pobierz kod z repozytorium
      uses: actions/checkout@v4

    - name: Ustaw środowisko Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # Instalujemy gradle w systemie Ubuntu, żeby móc wygenerować wrapper lokalnie w projekcie
    - name: Zainstaluj Gradle w systemie i wygeneruj Wrapper
      run: |
        sudo apt-get update && sudo apt-get install -y gradle
        gradle wrapper --gradle-version 8.2

    # Teraz plik 'gradlew' już istnieje na 100%, więc możemy nadać mu uprawnienia
    - name: Nadaj uprawnienia do uruchomienia Gradle
      run: chmod +x gradlew

    - name: Budowanie pliku APK (Debug)
      run: ./gradlew assembleDebug

    - name: Udostępnij gotowy plik APK
      uses: actions/upload-artifact@v4
      with:
        name: StatusLyrics-apk
        path: app/build/outputs/apk/debug/app-debug.apk
